# Edalize tool backend for Rivet testbenches.
#
# Registered through the ``edalize.legacy_tool`` entry point, so
# ``fusesoc run --tool rivet`` (and ``edalize`` scripts using
# ``get_edatool("rivet")``) find it after ``pip install``.

import logging
import os
import shutil
import subprocess

from edalize.edatool import Edatool

logger = logging.getLogger(__name__)

HDL_TYPES = {
    "verilogSource": "verilog",
    "verilogSource-95": "verilog",
    "verilogSource-2001": "verilog",
    "verilogSource-2005": "verilog",
    "systemVerilogSource": "verilog",
    "systemVerilogSource-3.0": "verilog",
    "systemVerilogSource-3.1": "verilog",
    "systemVerilogSource-3.1a": "verilog",
    "vhdlSource": "vhdl",
    "vhdlSource-87": "vhdl",
    "vhdlSource-93": "vhdl",
    "vhdlSource-2008": "vhdl",
}


def _toml_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


class Rivet(Edatool):
    """Run a Rivet (Rust) testbench against the core's HDL."""

    argtypes = ["plusarg", "vlogdefine", "vlogparam", "generic"]

    @classmethod
    def get_doc(cls, api_ver):
        if api_ver == 0:
            return {
                "description": "Rivet: Rust hardware-verification harness (cocotb replacement). "
                "Runs the core's Rust test crate on Icarus, Verilator or GHDL.",
                "members": [
                    {"name": "simulator", "type": "String", "desc": "icarus (default), verilator or ghdl"},
                    {"name": "crate", "type": "String", "desc": "Directory of the Rust test crate (default: directory of a listed Cargo.toml)"},
                    {"name": "rivet", "type": "String", "desc": "Path to the rivet executable"},
                ],
                "lists": [
                    {"name": "rivet_options", "type": "String", "desc": "Extra arguments for `rivet run`"},
                ],
            }

    # ------------------------------------------------------------------
    def _simulator(self):
        return self.tool_options.get("simulator", "icarus")

    def _rivet_bin(self):
        return self.tool_options.get("rivet") or os.environ.get("RIVET_BIN") or shutil.which("rivet") or "rivet"

    def _abs(self, name):
        return os.path.normpath(os.path.join(os.path.abspath(self.work_root), name))

    def _crate_dir(self):
        c = self.tool_options.get("crate")
        if c:
            return self._abs(c)
        for f in self.files:
            if os.path.basename(f["name"]) == "Cargo.toml":
                return os.path.dirname(self._abs(f["name"]))
        raise RuntimeError(
            "rivet: no test crate: set tool option `crate` or list the crate's Cargo.toml as a `user` file"
        )

    def _manifest_path(self):
        return os.path.join(os.path.abspath(self.work_root), "rivet.toml")

    # ------------------------------------------------------------------
    def configure_main(self):
        src_files, incdirs = self._get_fileset_files()
        sources = []
        language = None
        for f in src_files:
            lang = HDL_TYPES.get(f.file_type)
            if lang is None:
                if f.file_type not in ("user", ""):
                    logger.warning("rivet: ignoring %s (file type %s)", f.name, f.file_type)
                continue
            language = language or lang
            sources.append(self._abs(f.name))
        if not self.toplevel:
            raise RuntimeError("rivet: the target needs a toplevel")
        top = self.toplevel.split()[0]

        lines = ["# generated by edalize_rivet; edit the core file instead", "[design]"]
        lines.append(f"top = {_toml_str(top)}")
        lines.append("sources = [" + ", ".join(_toml_str(s) for s in sources) + "]")
        lines.append("includes = [" + ", ".join(_toml_str(self._abs(i)) for i in incdirs) + "]")
        if language:
            lines.append(f"language = {_toml_str(language)}")
        timescale = self.tool_options.get("timescale")
        if timescale:
            lines.append(f"timescale = {_toml_str(timescale)}")
        if self.vlogdefine:
            lines.append("")
            lines.append("[design.defines]")
            for k, v in self.vlogdefine.items():
                lines.append(f"{k} = {_toml_str(self._param_value_str(v, ''))}")
        params = dict(self.vlogparam)
        params.update(self.generic)
        if params:
            lines.append("")
            lines.append("[design.params]")
            for k, v in params.items():
                lines.append(f"{k} = {_toml_str(self._param_value_str(v, ''))}")
        sim = self._simulator()
        lines.append("")
        lines.append(f"[sim.{sim}]")
        plusargs = ["+{}={}".format(k, self._param_value_str(v)) for k, v in self.plusarg.items()]
        lines.append("run_args = [" + ", ".join(_toml_str(a) for a in plusargs) + "]")
        if sim == "verilator":
            lines.append("trace = true")
        with open(self._manifest_path(), "w") as f:
            f.write("\n".join(lines) + "\n")
        logger.info("rivet: wrote %s for crate %s", self._manifest_path(), self._crate_dir())

    def _rivet(self, cmd, extra):
        args = [self._rivet_bin(), cmd, "--sim", self._simulator(), "-C", self._crate_dir(), "--manifest", self._manifest_path()]
        args += list(self.tool_options.get("rivet_options", []))
        args += extra
        logger.info("rivet: %s", " ".join(args))
        env = dict(self.env)
        env.setdefault("CARGO_TARGET_DIR", os.path.join(os.path.abspath(self.work_root), "cargo-target"))
        subprocess.run(args, cwd=self.work_root, env=env, check=True)

    def build_main(self, target=None):
        self._rivet("build", [])

    def run_main(self):
        extra = []
        if self.plusarg:
            extra = ["--"] + ["+{}={}".format(k, self._param_value_str(v)) for k, v in self.plusarg.items()]
        self._rivet("run", extra)
