//! The functions a testbench calls: triggers, tasks, clocks, time,
//! logging and the ways a test can end.

use pyo3::exceptions::{PyRuntimeError, PyValueError};
use pyo3::prelude::*;
use rivet_core::backend::CbKind;
use rivet_core::runtime;
use rivet_core::time::{format_time, Unit};
use std::cell::RefCell;

use crate::handle::PySignal;
use crate::runtime_guard::{ensure_running, guard};
use crate::task::{PyTask, SkipTest, TestFailure, TestSuccess};
use crate::time as rtime;
use crate::trigger::{PyTrigger, TriggerKind};

/// Advance simulated time. `timer("10ns")` or `timer(10, "ns")`.
#[pyfunction]
#[pyo3(signature = (value, units = None))]
pub fn timer(value: &Bound<'_, PyAny>, units: Option<&str>) -> PyResult<PyTrigger> {
    Ok(PyTrigger::new(TriggerKind::Timer { duration: rtime::parse(value, units)? }))
}

/// Fires when values have settled in this time step. Writes are still
/// allowed.
#[pyfunction]
pub fn read_write() -> PyTrigger {
    PyTrigger::new(TriggerKind::Phase { kind: CbKind::ReadWrite })
}

/// Fires at the end of the time step, when every value is final. No
/// writes allowed until the next time step — this is where a check on
/// what the design just did belongs.
#[pyfunction]
pub fn read_only() -> PyTrigger {
    PyTrigger::new(TriggerKind::Phase { kind: CbKind::ReadOnly })
}

/// Fires at the beginning of the next time step.
#[pyfunction]
pub fn next_time_step() -> PyTrigger {
    PyTrigger::new(TriggerKind::Phase { kind: CbKind::NextTimeStep })
}

/// Let other ready tasks run. No simulated time passes.
#[pyfunction]
pub fn yield_now() -> PyTrigger {
    PyTrigger::new(TriggerKind::Yield)
}

/// Wait for `n` rising (or falling) edges of a clock, without returning
/// to Python in between.
#[pyfunction]
#[pyo3(signature = (signal, n = 1, rising = true))]
pub fn clock_cycles(signal: PyRef<'_, PySignal>, n: u64, rising: bool) -> PyTrigger {
    let kind = if rising { rivet_core::runtime::EdgeKind::Rising } else { rivet_core::runtime::EdgeKind::Falling };
    PyTrigger::new(TriggerKind::Edge { handle: signal.inner.handle(), kind, count: n.max(1) })
}

/// Whichever trigger fires first. Returns the index of the winner; the
/// others are dropped, which deregisters them.
#[pyfunction]
#[pyo3(signature = (*triggers))]
pub fn first(triggers: &Bound<'_, pyo3::types::PyTuple>) -> PyResult<PyTrigger> {
    let mut of = Vec::with_capacity(triggers.len());
    for t in triggers.iter() {
        let t: PyTrigger = t.extract().map_err(|_| {
            PyValueError::new_err("first() takes triggers — `await first(clk.rising_edge(), timer(\"1us\"))`")
        })?;
        of.push(t.kind);
    }
    if of.is_empty() {
        return Err(PyValueError::new_err("first() needs at least one trigger"));
    }
    Ok(PyTrigger::new(TriggerKind::First { of }))
}

/// Start `coro` as a task running alongside this one.
///
/// An exception escaping the task fails the test, as in cocotb. Pass
/// `propagate=False` when the caller intends to handle it via `join()`.
#[pyfunction]
#[pyo3(signature = (coro, name = None, propagate = true))]
pub fn start_soon(coro: Py<PyAny>, name: Option<String>, propagate: bool) -> PyResult<PyTask> {
    Python::with_gil(|py| -> PyResult<()> {
        let obj = coro.bind(py);
        if obj.hasattr(pyo3::intern!(py, "send")).unwrap_or(false) {
            return Ok(());
        }
        let what = obj.get_type().name().map(|n| n.to_string()).unwrap_or_else(|_| "that".into());
        Err(pyo3::exceptions::PyTypeError::new_err(format!(
            "start_soon() takes a coroutine — call the async function, as in \
             start_soon(monitor()), not start_soon(monitor). Got {what}."
        )))
    })?;
    let name = match name {
        Some(n) => n,
        None => Python::with_gil(|py| {
            coro.bind(py)
                .getattr("__name__")
                .and_then(|n| n.extract::<String>())
                .or_else(|_| {
                    coro.bind(py)
                        .getattr("cr_code")
                        .and_then(|c| c.getattr("co_name"))
                        .and_then(|n| n.extract::<String>())
                })
                .unwrap_or_else(|_| "task".to_string())
        }),
    };
    Ok(PyTask { state: crate::task::spawn(coro, name, propagate)? })
}

/// A free-running clock, generated by a native task: no Python runs per
/// edge, however many cycles the test takes.
#[pyclass(name = "Clock", module = "rivet", unsendable)]
pub struct PyClock {
    inner: RefCell<Option<rivet_core::clock::Clock>>,
    signal: rivet_core::handle::Signal,
    period: rivet_core::time::Duration,
    high: Option<rivet_core::time::Duration>,
    start_high: bool,
    phase: Option<rivet_core::time::Duration>,
    jitter: Option<rivet_core::time::Duration>,
    immediate: bool,
}

#[pymethods]
impl PyClock {
    #[new]
    #[pyo3(signature = (signal, period, units = None, *, high_time = None, start_high = true, phase = None, jitter = None, immediate = false))]
    #[allow(clippy::too_many_arguments)]
    fn new(
        signal: PyRef<'_, PySignal>,
        period: &Bound<'_, PyAny>,
        units: Option<&str>,
        high_time: Option<&Bound<'_, PyAny>>,
        start_high: bool,
        phase: Option<&Bound<'_, PyAny>>,
        jitter: Option<&Bound<'_, PyAny>>,
        immediate: bool,
    ) -> PyResult<PyClock> {
        let opt = |o: Option<&Bound<'_, PyAny>>| -> PyResult<Option<rivet_core::time::Duration>> {
            o.map(|v| rtime::parse(v, units)).transpose()
        };
        Ok(PyClock {
            inner: RefCell::new(None),
            signal: signal.inner,
            period: rtime::parse(period, units)?,
            high: opt(high_time)?,
            start_high,
            phase: opt(phase)?,
            jitter: opt(jitter)?,
            immediate,
        })
    }

    /// Start the clock. Returns self, so `clk = Clock(sig, "10ns").start()`
    /// reads as one line.
    fn start(slf: PyRefMut<'_, Self>) -> PyResult<PyRefMut<'_, Self>> {
        ensure_running()?;
        if slf.inner.borrow().is_some() {
            return Err(PyRuntimeError::new_err("this clock is already running"));
        }
        let mut b = rivet_core::clock::Clock::builder(slf.signal, slf.period).start_high(slf.start_high);
        if let Some(h) = slf.high {
            b = b.high_time(h);
        }
        if let Some(p) = slf.phase {
            b = b.phase(p);
        }
        if let Some(j) = slf.jitter {
            b = b.jitter(j);
        }
        if slf.immediate {
            b = b.immediate();
        }
        let clock = guard(|| b.start())?;
        *slf.inner.borrow_mut() = Some(clock);
        Ok(slf)
    }

    fn stop(&self) {
        if let Some(c) = self.inner.borrow().as_ref() {
            c.stop();
        }
    }

    /// Wait for `n` rising edges of this clock.
    #[pyo3(signature = (n = 1))]
    fn cycles(&self, n: u64) -> PyTrigger {
        PyTrigger::new(TriggerKind::Edge {
            handle: self.signal.handle(),
            kind: rivet_core::runtime::EdgeKind::Rising,
            count: n.max(1),
        })
    }

    #[getter]
    fn running(&self) -> bool {
        self.inner.borrow().is_some()
    }

    fn __repr__(&self) -> String {
        format!("<Clock {} period {}>", self.signal.path(), self.period)
    }
}

// ---------------------------------------------------------------------------
// Time

/// Simulated time now, in `units` (default: simulator steps).
#[pyfunction]
#[pyo3(signature = (units = None))]
pub fn now(units: Option<&str>) -> PyResult<f64> {
    let steps = crate::runtime_guard::now()?;
    let Some(u) = units else { return Ok(steps as f64) };
    let unit = rtime::unit_from_str(u).ok_or_else(|| PyValueError::new_err(format!("{u:?} is not a time unit")))?;
    let Some(exp) = unit.exponent() else { return Ok(steps as f64) };
    let precision = runtime::precision();
    Ok(steps as f64 * 10f64.powi(precision - exp))
}

/// Simulated time now, formatted the way the log formats it.
#[pyfunction]
pub fn now_str() -> PyResult<String> {
    let steps = crate::runtime_guard::now()?;
    Ok(format_time(steps, runtime::precision(), Unit::Ns))
}

/// The simulator's time precision, as a power of ten of seconds.
#[pyfunction]
pub fn precision() -> PyResult<i32> {
    crate::runtime_guard::precision()
}

/// Which simulator is running.
#[pyfunction]
pub fn simulator() -> PyResult<(String, String)> {
    ensure_running()?;
    Ok(runtime::backend(|b| (b.name().to_string(), b.version().to_string())))
}

// ---------------------------------------------------------------------------
// Ending a test

/// Fail the running test now.
#[pyfunction]
pub fn fail(msg: &str) -> PyResult<()> {
    Err(TestFailure::new_err(msg.to_string()))
}

/// Skip the running test.
#[pyfunction]
pub fn skip(why: &str) -> PyResult<()> {
    Err(SkipTest::new_err(why.to_string()))
}

/// End the running test as passed, from any task — cocotb's
/// `TestSuccess`. Raise the return value from the test body, or call
/// `finish_now()` from a background task.
#[pyfunction]
#[pyo3(signature = (why = "finished early"))]
pub fn finish(why: &str) -> PyResult<()> {
    Err(TestSuccess::new_err(why.to_string()))
}

/// End the running test as passed, from wherever this is called.
#[pyfunction]
pub fn finish_now() -> PyResult<()> {
    ensure_running()?;
    runtime::finish_test();
    Ok(())
}

/// Record a failure against the running test without unwinding.
#[pyfunction]
pub fn report_failure(msg: &str) -> PyResult<()> {
    ensure_running()?;
    runtime::report_failure(msg.to_string());
    Ok(())
}

/// Every live task and what it is waiting for — the same dump a timeout
/// prints.
#[pyfunction]
pub fn dump_tasks() -> PyResult<String> {
    ensure_running()?;
    guard(runtime::dump_tasks)
}

// ---------------------------------------------------------------------------
// Logging: Python messages go through Rivet's logger, so they interleave
// with the harness's own output and carry the simulated timestamp.

#[pyfunction]
pub fn log_message(level: &str, msg: &str) {
    match level {
        "debug" => log::debug!("{msg}"),
        "info" => log::info!("{msg}"),
        "warning" | "warn" => log::warn!("{msg}"),
        "error" => log::error!("{msg}"),
        _ => log::info!("{msg}"),
    }
}

/// The test's own seeded generator, reproducible from `--seed`.
#[pyfunction]
pub fn test_seed() -> u64 {
    rivet_core::random::test_seed()
}

#[pyfunction]
pub fn base_seed() -> u64 {
    rivet_core::random::base_seed()
}
