[package]
name = "example-conformance"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "conformance_verilator"
path = "src/main.rs"
required-features = ["verilator"]

[dependencies]
rivet = { workspace = true }
log = { workspace = true }

[build-dependencies]
rivet-verilator = { workspace = true }

[features]
verilator = ["rivet/verilator"]
