// Generated by `rivet bindgen`. Do not edit; regenerate when the design changes.
#![allow(non_snake_case, non_camel_case_types, dead_code, clippy::all)]

use rivet::{Bind, Module, Result, Signal};

fn bind_signal(m: &Module, name: &str, width: u32) -> Result<Signal> {
    let s = m.signal(name)?;
    if width != 0 && s.width() != width {
        return Err(rivet::Error::Msg(format!(
            "{}: expected width {width}, design has {}; regenerate bindings",
            s.path(),
            s.width()
        )));
    }
    Ok(s)
}

fn bind_array(m: &Module, name: &str, lo: i64, hi: i64) -> Result<Vec<Signal>> {
    let a = m.signal(name)?;
    (lo..=hi).map(|i| a.index(i)).collect()
}

/// `dff`
#[derive(Clone)]
pub struct Dff {
    pub module: Module,
    /// `clk`: Logic net, 1 bit(s)
    pub clk: Signal,
    /// `d`: LogicVec net, 8 bit(s)
    pub d: Signal,
    /// `mem_out`: LogicVec net, 8 bit(s)
    pub mem_out: Signal,
    /// `rst_n`: Logic net, 1 bit(s)
    pub rst_n: Signal,
    /// `sum`: LogicVec net, 9 bit(s)
    pub sum: Signal,
    /// `count`: LogicVec reg, 8 bit(s)
    pub count: Signal,
    /// `q`: LogicVec reg, 8 bit(s)
    pub q: Signal,
    /// `mem` [0..=3]
    pub mem: Vec<Signal>,
    /// `cycles`: Integer integer, 32 bit(s)
    pub cycles: Signal,
    /// `ratio`: Real real, 64 bit(s)
    pub ratio: Signal,
    /// `WIDTH`: LogicVec parameter, 32 bit(s)
    pub WIDTH: Signal,
}

impl Dff {
    pub fn from_module(module: Module) -> Result<Self> {
        Ok(Self {
            clk: bind_signal(&module, "clk", 1)?,
            d: bind_signal(&module, "d", 8)?,
            mem_out: bind_signal(&module, "mem_out", 8)?,
            rst_n: bind_signal(&module, "rst_n", 1)?,
            sum: bind_signal(&module, "sum", 9)?,
            count: bind_signal(&module, "count", 8)?,
            q: bind_signal(&module, "q", 8)?,
            mem: bind_array(&module, "mem", 0, 3)?,
            cycles: bind_signal(&module, "cycles", 32)?,
            ratio: bind_signal(&module, "ratio", 64)?,
            WIDTH: bind_signal(&module, "WIDTH", 32)?,
            module,
        })
    }
}

/// Alias for the top-level `Dff`.
pub type Dut = Dff;

impl Bind for Dff {
    fn bind(root: Module) -> Result<Self> {
        Self::from_module(root)
    }
}
