// Generated by `rivet bindgen`. Do not edit; regenerate when the design changes.
#![allow(non_snake_case, non_camel_case_types, dead_code, unused_imports, clippy::all)]

use rivet::{Bind, IntoLogicVec, LogicVec, Module, Result, Signal};

fn bind_signal(m: &Module, name: &str, width: u32) -> Result<Signal> {
    let s = m.signal(name)?;
    if width != 0 && s.width() != width {
        return Err(rivet::Error::Msg(format!(
            "{}: expected width {width}, design has {}; regenerate bindings",
            s.path(),
            s.width()
        )));
    }
    Ok(s)
}

fn bind_array(m: &Module, name: &str, lo: i64, hi: i64) -> Result<Vec<Signal>> {
    let a = m.signal(name)?;
    (lo..=hi).map(|i| a.index(i)).collect()
}

/// `bus_top.u_axil_slice`
#[derive(Clone)]
pub struct Bus_top_u_axil_slice {
    pub module: Module,
    /// `clk`: Logic net, 1 bit(s)
    pub clk: Signal,
    /// `m_arready`: Logic net, 1 bit(s)
    pub m_arready: Signal,
    /// `m_awready`: Logic net, 1 bit(s)
    pub m_awready: Signal,
    /// `m_bready`: Logic net, 1 bit(s)
    pub m_bready: Signal,
    /// `m_bresp`: LogicVec net, 2 bit(s)
    pub m_bresp: Signal,
    /// `m_bvalid`: Logic net, 1 bit(s)
    pub m_bvalid: Signal,
    /// `m_rdata`: LogicVec net, 32 bit(s)
    pub m_rdata: Signal,
    /// `m_rready`: Logic net, 1 bit(s)
    pub m_rready: Signal,
    /// `m_rresp`: LogicVec net, 2 bit(s)
    pub m_rresp: Signal,
    /// `m_rvalid`: Logic net, 1 bit(s)
    pub m_rvalid: Signal,
    /// `m_wready`: Logic net, 1 bit(s)
    pub m_wready: Signal,
    /// `rst_n`: Logic net, 1 bit(s)
    pub rst_n: Signal,
    /// `s_araddr`: LogicVec net, 32 bit(s)
    pub s_araddr: Signal,
    /// `s_arready`: Logic net, 1 bit(s)
    pub s_arready: Signal,
    /// `s_arvalid`: Logic net, 1 bit(s)
    pub s_arvalid: Signal,
    /// `s_awaddr`: LogicVec net, 32 bit(s)
    pub s_awaddr: Signal,
    /// `s_awready`: Logic net, 1 bit(s)
    pub s_awready: Signal,
    /// `s_awvalid`: Logic net, 1 bit(s)
    pub s_awvalid: Signal,
    /// `s_bready`: Logic net, 1 bit(s)
    pub s_bready: Signal,
    /// `s_rready`: Logic net, 1 bit(s)
    pub s_rready: Signal,
    /// `s_wdata`: LogicVec net, 32 bit(s)
    pub s_wdata: Signal,
    /// `s_wready`: Logic net, 1 bit(s)
    pub s_wready: Signal,
    /// `s_wstrb`: LogicVec net, 4 bit(s)
    pub s_wstrb: Signal,
    /// `s_wvalid`: Logic net, 1 bit(s)
    pub s_wvalid: Signal,
    /// `m_araddr`: LogicVec reg, 32 bit(s)
    pub m_araddr: Signal,
    /// `m_arvalid`: Logic reg, 1 bit(s)
    pub m_arvalid: Signal,
    /// `m_awaddr`: LogicVec reg, 32 bit(s)
    pub m_awaddr: Signal,
    /// `m_awvalid`: Logic reg, 1 bit(s)
    pub m_awvalid: Signal,
    /// `m_wdata`: LogicVec reg, 32 bit(s)
    pub m_wdata: Signal,
    /// `m_wstrb`: LogicVec reg, 4 bit(s)
    pub m_wstrb: Signal,
    /// `m_wvalid`: Logic reg, 1 bit(s)
    pub m_wvalid: Signal,
    /// `s_bresp`: LogicVec reg, 2 bit(s)
    pub s_bresp: Signal,
    /// `s_bvalid`: Logic reg, 1 bit(s)
    pub s_bvalid: Signal,
    /// `s_rdata`: LogicVec reg, 32 bit(s)
    pub s_rdata: Signal,
    /// `s_rresp`: LogicVec reg, 2 bit(s)
    pub s_rresp: Signal,
    /// `s_rvalid`: Logic reg, 1 bit(s)
    pub s_rvalid: Signal,
}

impl Bus_top_u_axil_slice {
    pub fn from_module(module: Module) -> Result<Self> {
        Ok(Self {
            clk: bind_signal(&module, "clk", 1)?,
            m_arready: bind_signal(&module, "m_arready", 1)?,
            m_awready: bind_signal(&module, "m_awready", 1)?,
            m_bready: bind_signal(&module, "m_bready", 1)?,
            m_bresp: bind_signal(&module, "m_bresp", 2)?,
            m_bvalid: bind_signal(&module, "m_bvalid", 1)?,
            m_rdata: bind_signal(&module, "m_rdata", 32)?,
            m_rready: bind_signal(&module, "m_rready", 1)?,
            m_rresp: bind_signal(&module, "m_rresp", 2)?,
            m_rvalid: bind_signal(&module, "m_rvalid", 1)?,
            m_wready: bind_signal(&module, "m_wready", 1)?,
            rst_n: bind_signal(&module, "rst_n", 1)?,
            s_araddr: bind_signal(&module, "s_araddr", 32)?,
            s_arready: bind_signal(&module, "s_arready", 1)?,
            s_arvalid: bind_signal(&module, "s_arvalid", 1)?,
            s_awaddr: bind_signal(&module, "s_awaddr", 32)?,
            s_awready: bind_signal(&module, "s_awready", 1)?,
            s_awvalid: bind_signal(&module, "s_awvalid", 1)?,
            s_bready: bind_signal(&module, "s_bready", 1)?,
            s_rready: bind_signal(&module, "s_rready", 1)?,
            s_wdata: bind_signal(&module, "s_wdata", 32)?,
            s_wready: bind_signal(&module, "s_wready", 1)?,
            s_wstrb: bind_signal(&module, "s_wstrb", 4)?,
            s_wvalid: bind_signal(&module, "s_wvalid", 1)?,
            m_araddr: bind_signal(&module, "m_araddr", 32)?,
            m_arvalid: bind_signal(&module, "m_arvalid", 1)?,
            m_awaddr: bind_signal(&module, "m_awaddr", 32)?,
            m_awvalid: bind_signal(&module, "m_awvalid", 1)?,
            m_wdata: bind_signal(&module, "m_wdata", 32)?,
            m_wstrb: bind_signal(&module, "m_wstrb", 4)?,
            m_wvalid: bind_signal(&module, "m_wvalid", 1)?,
            s_bresp: bind_signal(&module, "s_bresp", 2)?,
            s_bvalid: bind_signal(&module, "s_bvalid", 1)?,
            s_rdata: bind_signal(&module, "s_rdata", 32)?,
            s_rresp: bind_signal(&module, "s_rresp", 2)?,
            s_rvalid: bind_signal(&module, "s_rvalid", 1)?,
            module,
        })
    }
}

/// `bus_top`
#[derive(Clone)]
pub struct Bus_top {
    pub module: Module,
    /// `apb_paddr`: LogicVec net, 16 bit(s)
    pub apb_paddr: Signal,
    /// `apb_penable`: Logic net, 1 bit(s)
    pub apb_penable: Signal,
    /// `apb_psel`: Logic net, 1 bit(s)
    pub apb_psel: Signal,
    /// `apb_pstrb`: LogicVec net, 4 bit(s)
    pub apb_pstrb: Signal,
    /// `apb_pwdata`: LogicVec net, 32 bit(s)
    pub apb_pwdata: Signal,
    /// `apb_pwrite`: Logic net, 1 bit(s)
    pub apb_pwrite: Signal,
    /// `av_address`: LogicVec net, 16 bit(s)
    pub av_address: Signal,
    /// `av_byteenable`: LogicVec net, 4 bit(s)
    pub av_byteenable: Signal,
    /// `av_read`: Logic net, 1 bit(s)
    pub av_read: Signal,
    /// `av_write`: Logic net, 1 bit(s)
    pub av_write: Signal,
    /// `av_writedata`: LogicVec net, 32 bit(s)
    pub av_writedata: Signal,
    /// `clk`: Logic net, 1 bit(s)
    pub clk: Signal,
    /// `cmd`: LogicVec net, 18 bit(s)
    pub cmd: Signal,
    /// `m_axis_tready`: Logic net, 1 bit(s)
    pub m_axis_tready: Signal,
    /// `p_axil_araddr`: LogicVec net, 32 bit(s)
    pub p_axil_araddr: Signal,
    /// `p_axil_arvalid`: Logic net, 1 bit(s)
    pub p_axil_arvalid: Signal,
    /// `p_axil_awaddr`: LogicVec net, 32 bit(s)
    pub p_axil_awaddr: Signal,
    /// `p_axil_awvalid`: Logic net, 1 bit(s)
    pub p_axil_awvalid: Signal,
    /// `p_axil_bready`: Logic net, 1 bit(s)
    pub p_axil_bready: Signal,
    /// `p_axil_rready`: Logic net, 1 bit(s)
    pub p_axil_rready: Signal,
    /// `p_axil_wdata`: LogicVec net, 32 bit(s)
    pub p_axil_wdata: Signal,
    /// `p_axil_wstrb`: LogicVec net, 4 bit(s)
    pub p_axil_wstrb: Signal,
    /// `p_axil_wvalid`: Logic net, 1 bit(s)
    pub p_axil_wvalid: Signal,
    /// `q_axil_arready`: Logic net, 1 bit(s)
    pub q_axil_arready: Signal,
    /// `q_axil_awready`: Logic net, 1 bit(s)
    pub q_axil_awready: Signal,
    /// `q_axil_bresp`: LogicVec net, 2 bit(s)
    pub q_axil_bresp: Signal,
    /// `q_axil_bvalid`: Logic net, 1 bit(s)
    pub q_axil_bvalid: Signal,
    /// `q_axil_rdata`: LogicVec net, 32 bit(s)
    pub q_axil_rdata: Signal,
    /// `q_axil_rresp`: LogicVec net, 2 bit(s)
    pub q_axil_rresp: Signal,
    /// `q_axil_rvalid`: Logic net, 1 bit(s)
    pub q_axil_rvalid: Signal,
    /// `q_axil_wready`: Logic net, 1 bit(s)
    pub q_axil_wready: Signal,
    /// `rst_n`: Logic net, 1 bit(s)
    pub rst_n: Signal,
    /// `s_axi_araddr`: LogicVec net, 32 bit(s)
    pub s_axi_araddr: Signal,
    /// `s_axi_arburst`: LogicVec net, 2 bit(s)
    pub s_axi_arburst: Signal,
    /// `s_axi_arid`: LogicVec net, 4 bit(s)
    pub s_axi_arid: Signal,
    /// `s_axi_arlen`: LogicVec net, 8 bit(s)
    pub s_axi_arlen: Signal,
    /// `s_axi_arsize`: LogicVec net, 3 bit(s)
    pub s_axi_arsize: Signal,
    /// `s_axi_arvalid`: Logic net, 1 bit(s)
    pub s_axi_arvalid: Signal,
    /// `s_axi_awaddr`: LogicVec net, 32 bit(s)
    pub s_axi_awaddr: Signal,
    /// `s_axi_awburst`: LogicVec net, 2 bit(s)
    pub s_axi_awburst: Signal,
    /// `s_axi_awid`: LogicVec net, 4 bit(s)
    pub s_axi_awid: Signal,
    /// `s_axi_awlen`: LogicVec net, 8 bit(s)
    pub s_axi_awlen: Signal,
    /// `s_axi_awready`: Logic net, 1 bit(s)
    pub s_axi_awready: Signal,
    /// `s_axi_awsize`: LogicVec net, 3 bit(s)
    pub s_axi_awsize: Signal,
    /// `s_axi_awvalid`: Logic net, 1 bit(s)
    pub s_axi_awvalid: Signal,
    /// `s_axi_bready`: Logic net, 1 bit(s)
    pub s_axi_bready: Signal,
    /// `s_axi_rready`: Logic net, 1 bit(s)
    pub s_axi_rready: Signal,
    /// `s_axi_wdata`: LogicVec net, 32 bit(s)
    pub s_axi_wdata: Signal,
    /// `s_axi_wlast`: Logic net, 1 bit(s)
    pub s_axi_wlast: Signal,
    /// `s_axi_wready`: Logic net, 1 bit(s)
    pub s_axi_wready: Signal,
    /// `s_axi_wstrb`: LogicVec net, 4 bit(s)
    pub s_axi_wstrb: Signal,
    /// `s_axi_wvalid`: Logic net, 1 bit(s)
    pub s_axi_wvalid: Signal,
    /// `s_axil_araddr`: LogicVec net, 32 bit(s)
    pub s_axil_araddr: Signal,
    /// `s_axil_arvalid`: Logic net, 1 bit(s)
    pub s_axil_arvalid: Signal,
    /// `s_axil_awaddr`: LogicVec net, 32 bit(s)
    pub s_axil_awaddr: Signal,
    /// `s_axil_awvalid`: Logic net, 1 bit(s)
    pub s_axil_awvalid: Signal,
    /// `s_axil_bready`: Logic net, 1 bit(s)
    pub s_axil_bready: Signal,
    /// `s_axil_rready`: Logic net, 1 bit(s)
    pub s_axil_rready: Signal,
    /// `s_axil_wdata`: LogicVec net, 32 bit(s)
    pub s_axil_wdata: Signal,
    /// `s_axil_wstrb`: LogicVec net, 4 bit(s)
    pub s_axil_wstrb: Signal,
    /// `s_axil_wvalid`: Logic net, 1 bit(s)
    pub s_axil_wvalid: Signal,
    /// `s_axis_tdata`: LogicVec net, 32 bit(s)
    pub s_axis_tdata: Signal,
    /// `s_axis_tkeep`: LogicVec net, 4 bit(s)
    pub s_axis_tkeep: Signal,
    /// `s_axis_tlast`: Logic net, 1 bit(s)
    pub s_axis_tlast: Signal,
    /// `s_axis_tvalid`: Logic net, 1 bit(s)
    pub s_axis_tvalid: Signal,
    /// `wb_adr`: LogicVec net, 16 bit(s)
    pub wb_adr: Signal,
    /// `wb_cyc`: Logic net, 1 bit(s)
    pub wb_cyc: Signal,
    /// `wb_dat_w`: LogicVec net, 32 bit(s)
    pub wb_dat_w: Signal,
    /// `wb_sel`: LogicVec net, 4 bit(s)
    pub wb_sel: Signal,
    /// `wb_stb`: Logic net, 1 bit(s)
    pub wb_stb: Signal,
    /// `wb_we`: Logic net, 1 bit(s)
    pub wb_we: Signal,
    /// `s_axis_tready`: Logic net, 1 bit(s)
    pub s_axis_tready: Signal,
    /// `s_axil_wready`: Logic net, 1 bit(s)
    pub s_axil_wready: Signal,
    /// `s_axil_awready`: Logic net, 1 bit(s)
    pub s_axil_awready: Signal,
    /// `s_axil_arready`: Logic net, 1 bit(s)
    pub s_axil_arready: Signal,
    /// `s_axi_arready`: Logic net, 1 bit(s)
    pub s_axi_arready: Signal,
    /// `q_axil_wvalid`: Logic net, 1 bit(s)
    pub q_axil_wvalid: Signal,
    /// `q_axil_wstrb`: LogicVec net, 4 bit(s)
    pub q_axil_wstrb: Signal,
    /// `q_axil_wdata`: LogicVec net, 32 bit(s)
    pub q_axil_wdata: Signal,
    /// `q_axil_rready`: Logic net, 1 bit(s)
    pub q_axil_rready: Signal,
    /// `q_axil_bready`: Logic net, 1 bit(s)
    pub q_axil_bready: Signal,
    /// `q_axil_awvalid`: Logic net, 1 bit(s)
    pub q_axil_awvalid: Signal,
    /// `q_axil_awaddr`: LogicVec net, 32 bit(s)
    pub q_axil_awaddr: Signal,
    /// `q_axil_arvalid`: Logic net, 1 bit(s)
    pub q_axil_arvalid: Signal,
    /// `q_axil_araddr`: LogicVec net, 32 bit(s)
    pub q_axil_araddr: Signal,
    /// `p_axil_wready`: Logic net, 1 bit(s)
    pub p_axil_wready: Signal,
    /// `p_axil_rvalid`: Logic net, 1 bit(s)
    pub p_axil_rvalid: Signal,
    /// `p_axil_rresp`: LogicVec net, 2 bit(s)
    pub p_axil_rresp: Signal,
    /// `p_axil_rdata`: LogicVec net, 32 bit(s)
    pub p_axil_rdata: Signal,
    /// `p_axil_bvalid`: Logic net, 1 bit(s)
    pub p_axil_bvalid: Signal,
    /// `p_axil_bresp`: LogicVec net, 2 bit(s)
    pub p_axil_bresp: Signal,
    /// `p_axil_awready`: Logic net, 1 bit(s)
    pub p_axil_awready: Signal,
    /// `p_axil_arready`: Logic net, 1 bit(s)
    pub p_axil_arready: Signal,
    /// `av_waitrequest`: Logic net, 1 bit(s)
    pub av_waitrequest: Signal,
    /// `alu_out`: LogicVec reg, 16 bit(s)
    pub alu_out: Signal,
    /// `apb_prdata`: LogicVec reg, 32 bit(s)
    pub apb_prdata: Signal,
    /// `apb_pready`: Logic reg, 1 bit(s)
    pub apb_pready: Signal,
    /// `apb_pslverr`: Logic reg, 1 bit(s)
    pub apb_pslverr: Signal,
    /// `apb_wait`: Logic reg, 1 bit(s)
    pub apb_wait: Signal,
    /// `av_busy`: Logic reg, 1 bit(s)
    pub av_busy: Signal,
    /// `av_readdata`: LogicVec reg, 32 bit(s)
    pub av_readdata: Signal,
    /// `av_readdatavalid`: Logic reg, 1 bit(s)
    pub av_readdatavalid: Signal,
    /// `aw_addr`: LogicVec reg, 32 bit(s)
    pub aw_addr: Signal,
    /// `aw_pending`: Logic reg, 1 bit(s)
    pub aw_pending: Signal,
    /// `m_axis_tdata`: LogicVec reg, 32 bit(s)
    pub m_axis_tdata: Signal,
    /// `m_axis_tkeep`: LogicVec reg, 4 bit(s)
    pub m_axis_tkeep: Signal,
    /// `m_axis_tlast`: Logic reg, 1 bit(s)
    pub m_axis_tlast: Signal,
    /// `m_axis_tvalid`: Logic reg, 1 bit(s)
    pub m_axis_tvalid: Signal,
    /// `rd_active`: Logic reg, 1 bit(s)
    pub rd_active: Signal,
    /// `rd_addr`: LogicVec reg, 32 bit(s)
    pub rd_addr: Signal,
    /// `rd_beat`: LogicVec reg, 8 bit(s)
    pub rd_beat: Signal,
    /// `rd_burst`: LogicVec reg, 2 bit(s)
    pub rd_burst: Signal,
    /// `rd_id`: LogicVec reg, 4 bit(s)
    pub rd_id: Signal,
    /// `rd_len`: LogicVec reg, 8 bit(s)
    pub rd_len: Signal,
    /// `rd_size`: LogicVec reg, 3 bit(s)
    pub rd_size: Signal,
    /// `rd_start`: LogicVec reg, 32 bit(s)
    pub rd_start: Signal,
    /// `s_axi_bid`: LogicVec reg, 4 bit(s)
    pub s_axi_bid: Signal,
    /// `s_axi_bresp`: LogicVec reg, 2 bit(s)
    pub s_axi_bresp: Signal,
    /// `s_axi_bvalid`: Logic reg, 1 bit(s)
    pub s_axi_bvalid: Signal,
    /// `s_axi_rdata`: LogicVec reg, 32 bit(s)
    pub s_axi_rdata: Signal,
    /// `s_axi_rid`: LogicVec reg, 4 bit(s)
    pub s_axi_rid: Signal,
    /// `s_axi_rlast`: Logic reg, 1 bit(s)
    pub s_axi_rlast: Signal,
    /// `s_axi_rresp`: LogicVec reg, 2 bit(s)
    pub s_axi_rresp: Signal,
    /// `s_axi_rvalid`: Logic reg, 1 bit(s)
    pub s_axi_rvalid: Signal,
    /// `s_axil_bresp`: LogicVec reg, 2 bit(s)
    pub s_axil_bresp: Signal,
    /// `s_axil_bvalid`: Logic reg, 1 bit(s)
    pub s_axil_bvalid: Signal,
    /// `s_axil_rdata`: LogicVec reg, 32 bit(s)
    pub s_axil_rdata: Signal,
    /// `s_axil_rresp`: LogicVec reg, 2 bit(s)
    pub s_axil_rresp: Signal,
    /// `s_axil_rvalid`: Logic reg, 1 bit(s)
    pub s_axil_rvalid: Signal,
    /// `skid_data`: LogicVec reg, 32 bit(s)
    pub skid_data: Signal,
    /// `skid_keep`: LogicVec reg, 4 bit(s)
    pub skid_keep: Signal,
    /// `skid_last`: Logic reg, 1 bit(s)
    pub skid_last: Signal,
    /// `skid_valid`: Logic reg, 1 bit(s)
    pub skid_valid: Signal,
    /// `w_data`: LogicVec reg, 32 bit(s)
    pub w_data: Signal,
    /// `w_pending`: Logic reg, 1 bit(s)
    pub w_pending: Signal,
    /// `w_strb`: LogicVec reg, 4 bit(s)
    pub w_strb: Signal,
    /// `wb_ack`: Logic reg, 1 bit(s)
    pub wb_ack: Signal,
    /// `wb_dat_r`: LogicVec reg, 32 bit(s)
    pub wb_dat_r: Signal,
    /// `wb_err`: Logic reg, 1 bit(s)
    pub wb_err: Signal,
    /// `wr_active`: Logic reg, 1 bit(s)
    pub wr_active: Signal,
    /// `wr_addr`: LogicVec reg, 32 bit(s)
    pub wr_addr: Signal,
    /// `wr_beat`: LogicVec reg, 8 bit(s)
    pub wr_beat: Signal,
    /// `wr_burst`: LogicVec reg, 2 bit(s)
    pub wr_burst: Signal,
    /// `wr_id`: LogicVec reg, 4 bit(s)
    pub wr_id: Signal,
    /// `wr_len`: LogicVec reg, 8 bit(s)
    pub wr_len: Signal,
    /// `wr_size`: LogicVec reg, 3 bit(s)
    pub wr_size: Signal,
    /// `wr_start`: LogicVec reg, 32 bit(s)
    pub wr_start: Signal,
    /// `apb_regs` [0..=3]
    pub apb_regs: Vec<Signal>,
    /// `av_regs` [0..=3]
    pub av_regs: Vec<Signal>,
    /// `mem` [0..=255]
    pub mem: Vec<Signal>,
    /// `regs` [0..=7]
    pub regs: Vec<Signal>,
    /// `wb_regs` [0..=3]
    pub wb_regs: Vec<Signal>,
    /// `REG_INIT`: LogicVec parameter, 32 bit(s)
    pub REG_INIT: Signal,
    /// `u_axil_slice`
    pub u_axil_slice: Bus_top_u_axil_slice,
}

impl Bus_top {
    pub fn from_module(module: Module) -> Result<Self> {
        Ok(Self {
            apb_paddr: bind_signal(&module, "apb_paddr", 16)?,
            apb_penable: bind_signal(&module, "apb_penable", 1)?,
            apb_psel: bind_signal(&module, "apb_psel", 1)?,
            apb_pstrb: bind_signal(&module, "apb_pstrb", 4)?,
            apb_pwdata: bind_signal(&module, "apb_pwdata", 32)?,
            apb_pwrite: bind_signal(&module, "apb_pwrite", 1)?,
            av_address: bind_signal(&module, "av_address", 16)?,
            av_byteenable: bind_signal(&module, "av_byteenable", 4)?,
            av_read: bind_signal(&module, "av_read", 1)?,
            av_write: bind_signal(&module, "av_write", 1)?,
            av_writedata: bind_signal(&module, "av_writedata", 32)?,
            clk: bind_signal(&module, "clk", 1)?,
            cmd: bind_signal(&module, "cmd", 18)?,
            m_axis_tready: bind_signal(&module, "m_axis_tready", 1)?,
            p_axil_araddr: bind_signal(&module, "p_axil_araddr", 32)?,
            p_axil_arvalid: bind_signal(&module, "p_axil_arvalid", 1)?,
            p_axil_awaddr: bind_signal(&module, "p_axil_awaddr", 32)?,
            p_axil_awvalid: bind_signal(&module, "p_axil_awvalid", 1)?,
            p_axil_bready: bind_signal(&module, "p_axil_bready", 1)?,
            p_axil_rready: bind_signal(&module, "p_axil_rready", 1)?,
            p_axil_wdata: bind_signal(&module, "p_axil_wdata", 32)?,
            p_axil_wstrb: bind_signal(&module, "p_axil_wstrb", 4)?,
            p_axil_wvalid: bind_signal(&module, "p_axil_wvalid", 1)?,
            q_axil_arready: bind_signal(&module, "q_axil_arready", 1)?,
            q_axil_awready: bind_signal(&module, "q_axil_awready", 1)?,
            q_axil_bresp: bind_signal(&module, "q_axil_bresp", 2)?,
            q_axil_bvalid: bind_signal(&module, "q_axil_bvalid", 1)?,
            q_axil_rdata: bind_signal(&module, "q_axil_rdata", 32)?,
            q_axil_rresp: bind_signal(&module, "q_axil_rresp", 2)?,
            q_axil_rvalid: bind_signal(&module, "q_axil_rvalid", 1)?,
            q_axil_wready: bind_signal(&module, "q_axil_wready", 1)?,
            rst_n: bind_signal(&module, "rst_n", 1)?,
            s_axi_araddr: bind_signal(&module, "s_axi_araddr", 32)?,
            s_axi_arburst: bind_signal(&module, "s_axi_arburst", 2)?,
            s_axi_arid: bind_signal(&module, "s_axi_arid", 4)?,
            s_axi_arlen: bind_signal(&module, "s_axi_arlen", 8)?,
            s_axi_arsize: bind_signal(&module, "s_axi_arsize", 3)?,
            s_axi_arvalid: bind_signal(&module, "s_axi_arvalid", 1)?,
            s_axi_awaddr: bind_signal(&module, "s_axi_awaddr", 32)?,
            s_axi_awburst: bind_signal(&module, "s_axi_awburst", 2)?,
            s_axi_awid: bind_signal(&module, "s_axi_awid", 4)?,
            s_axi_awlen: bind_signal(&module, "s_axi_awlen", 8)?,
            s_axi_awready: bind_signal(&module, "s_axi_awready", 1)?,
            s_axi_awsize: bind_signal(&module, "s_axi_awsize", 3)?,
            s_axi_awvalid: bind_signal(&module, "s_axi_awvalid", 1)?,
            s_axi_bready: bind_signal(&module, "s_axi_bready", 1)?,
            s_axi_rready: bind_signal(&module, "s_axi_rready", 1)?,
            s_axi_wdata: bind_signal(&module, "s_axi_wdata", 32)?,
            s_axi_wlast: bind_signal(&module, "s_axi_wlast", 1)?,
            s_axi_wready: bind_signal(&module, "s_axi_wready", 1)?,
            s_axi_wstrb: bind_signal(&module, "s_axi_wstrb", 4)?,
            s_axi_wvalid: bind_signal(&module, "s_axi_wvalid", 1)?,
            s_axil_araddr: bind_signal(&module, "s_axil_araddr", 32)?,
            s_axil_arvalid: bind_signal(&module, "s_axil_arvalid", 1)?,
            s_axil_awaddr: bind_signal(&module, "s_axil_awaddr", 32)?,
            s_axil_awvalid: bind_signal(&module, "s_axil_awvalid", 1)?,
            s_axil_bready: bind_signal(&module, "s_axil_bready", 1)?,
            s_axil_rready: bind_signal(&module, "s_axil_rready", 1)?,
            s_axil_wdata: bind_signal(&module, "s_axil_wdata", 32)?,
            s_axil_wstrb: bind_signal(&module, "s_axil_wstrb", 4)?,
            s_axil_wvalid: bind_signal(&module, "s_axil_wvalid", 1)?,
            s_axis_tdata: bind_signal(&module, "s_axis_tdata", 32)?,
            s_axis_tkeep: bind_signal(&module, "s_axis_tkeep", 4)?,
            s_axis_tlast: bind_signal(&module, "s_axis_tlast", 1)?,
            s_axis_tvalid: bind_signal(&module, "s_axis_tvalid", 1)?,
            wb_adr: bind_signal(&module, "wb_adr", 16)?,
            wb_cyc: bind_signal(&module, "wb_cyc", 1)?,
            wb_dat_w: bind_signal(&module, "wb_dat_w", 32)?,
            wb_sel: bind_signal(&module, "wb_sel", 4)?,
            wb_stb: bind_signal(&module, "wb_stb", 1)?,
            wb_we: bind_signal(&module, "wb_we", 1)?,
            s_axis_tready: bind_signal(&module, "s_axis_tready", 1)?,
            s_axil_wready: bind_signal(&module, "s_axil_wready", 1)?,
            s_axil_awready: bind_signal(&module, "s_axil_awready", 1)?,
            s_axil_arready: bind_signal(&module, "s_axil_arready", 1)?,
            s_axi_arready: bind_signal(&module, "s_axi_arready", 1)?,
            q_axil_wvalid: bind_signal(&module, "q_axil_wvalid", 1)?,
            q_axil_wstrb: bind_signal(&module, "q_axil_wstrb", 4)?,
            q_axil_wdata: bind_signal(&module, "q_axil_wdata", 32)?,
            q_axil_rready: bind_signal(&module, "q_axil_rready", 1)?,
            q_axil_bready: bind_signal(&module, "q_axil_bready", 1)?,
            q_axil_awvalid: bind_signal(&module, "q_axil_awvalid", 1)?,
            q_axil_awaddr: bind_signal(&module, "q_axil_awaddr", 32)?,
            q_axil_arvalid: bind_signal(&module, "q_axil_arvalid", 1)?,
            q_axil_araddr: bind_signal(&module, "q_axil_araddr", 32)?,
            p_axil_wready: bind_signal(&module, "p_axil_wready", 1)?,
            p_axil_rvalid: bind_signal(&module, "p_axil_rvalid", 1)?,
            p_axil_rresp: bind_signal(&module, "p_axil_rresp", 2)?,
            p_axil_rdata: bind_signal(&module, "p_axil_rdata", 32)?,
            p_axil_bvalid: bind_signal(&module, "p_axil_bvalid", 1)?,
            p_axil_bresp: bind_signal(&module, "p_axil_bresp", 2)?,
            p_axil_awready: bind_signal(&module, "p_axil_awready", 1)?,
            p_axil_arready: bind_signal(&module, "p_axil_arready", 1)?,
            av_waitrequest: bind_signal(&module, "av_waitrequest", 1)?,
            alu_out: bind_signal(&module, "alu_out", 16)?,
            apb_prdata: bind_signal(&module, "apb_prdata", 32)?,
            apb_pready: bind_signal(&module, "apb_pready", 1)?,
            apb_pslverr: bind_signal(&module, "apb_pslverr", 1)?,
            apb_wait: bind_signal(&module, "apb_wait", 1)?,
            av_busy: bind_signal(&module, "av_busy", 1)?,
            av_readdata: bind_signal(&module, "av_readdata", 32)?,
            av_readdatavalid: bind_signal(&module, "av_readdatavalid", 1)?,
            aw_addr: bind_signal(&module, "aw_addr", 32)?,
            aw_pending: bind_signal(&module, "aw_pending", 1)?,
            m_axis_tdata: bind_signal(&module, "m_axis_tdata", 32)?,
            m_axis_tkeep: bind_signal(&module, "m_axis_tkeep", 4)?,
            m_axis_tlast: bind_signal(&module, "m_axis_tlast", 1)?,
            m_axis_tvalid: bind_signal(&module, "m_axis_tvalid", 1)?,
            rd_active: bind_signal(&module, "rd_active", 1)?,
            rd_addr: bind_signal(&module, "rd_addr", 32)?,
            rd_beat: bind_signal(&module, "rd_beat", 8)?,
            rd_burst: bind_signal(&module, "rd_burst", 2)?,
            rd_id: bind_signal(&module, "rd_id", 4)?,
            rd_len: bind_signal(&module, "rd_len", 8)?,
            rd_size: bind_signal(&module, "rd_size", 3)?,
            rd_start: bind_signal(&module, "rd_start", 32)?,
            s_axi_bid: bind_signal(&module, "s_axi_bid", 4)?,
            s_axi_bresp: bind_signal(&module, "s_axi_bresp", 2)?,
            s_axi_bvalid: bind_signal(&module, "s_axi_bvalid", 1)?,
            s_axi_rdata: bind_signal(&module, "s_axi_rdata", 32)?,
            s_axi_rid: bind_signal(&module, "s_axi_rid", 4)?,
            s_axi_rlast: bind_signal(&module, "s_axi_rlast", 1)?,
            s_axi_rresp: bind_signal(&module, "s_axi_rresp", 2)?,
            s_axi_rvalid: bind_signal(&module, "s_axi_rvalid", 1)?,
            s_axil_bresp: bind_signal(&module, "s_axil_bresp", 2)?,
            s_axil_bvalid: bind_signal(&module, "s_axil_bvalid", 1)?,
            s_axil_rdata: bind_signal(&module, "s_axil_rdata", 32)?,
            s_axil_rresp: bind_signal(&module, "s_axil_rresp", 2)?,
            s_axil_rvalid: bind_signal(&module, "s_axil_rvalid", 1)?,
            skid_data: bind_signal(&module, "skid_data", 32)?,
            skid_keep: bind_signal(&module, "skid_keep", 4)?,
            skid_last: bind_signal(&module, "skid_last", 1)?,
            skid_valid: bind_signal(&module, "skid_valid", 1)?,
            w_data: bind_signal(&module, "w_data", 32)?,
            w_pending: bind_signal(&module, "w_pending", 1)?,
            w_strb: bind_signal(&module, "w_strb", 4)?,
            wb_ack: bind_signal(&module, "wb_ack", 1)?,
            wb_dat_r: bind_signal(&module, "wb_dat_r", 32)?,
            wb_err: bind_signal(&module, "wb_err", 1)?,
            wr_active: bind_signal(&module, "wr_active", 1)?,
            wr_addr: bind_signal(&module, "wr_addr", 32)?,
            wr_beat: bind_signal(&module, "wr_beat", 8)?,
            wr_burst: bind_signal(&module, "wr_burst", 2)?,
            wr_id: bind_signal(&module, "wr_id", 4)?,
            wr_len: bind_signal(&module, "wr_len", 8)?,
            wr_size: bind_signal(&module, "wr_size", 3)?,
            wr_start: bind_signal(&module, "wr_start", 32)?,
            apb_regs: bind_array(&module, "apb_regs", 0, 3)?,
            av_regs: bind_array(&module, "av_regs", 0, 3)?,
            mem: bind_array(&module, "mem", 0, 255)?,
            regs: bind_array(&module, "regs", 0, 7)?,
            wb_regs: bind_array(&module, "wb_regs", 0, 3)?,
            REG_INIT: bind_signal(&module, "REG_INIT", 32)?,
            u_axil_slice: Bus_top_u_axil_slice::from_module(module.module("u_axil_slice")?)?,
            module,
        })
    }
}

/// Alias for the top-level `Bus_top`.
pub type Dut = Bus_top;

impl Bind for Bus_top {
    fn bind(root: Module) -> Result<Self> {
        Self::from_module(root)
    }
}

impl Bus_top {
    /// The design below this instance as an indented tree.
    pub fn hierarchy(&self) -> String {
        rivet::test::format_hierarchy(self.module)
    }
}

// ---- typedefs from the design sources ----

/// `typedef enum` `op_t` (2 bits)
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
#[repr(u64)]
pub enum Op {
    OP_NOP = 0,
    OP_ADD = 1,
    OP_SUB = 2,
    OP_MUL = 3,
}

impl Op {
    pub const WIDTH: u32 = 2;
    pub const ALL: &'static [Op] = &[Op::OP_NOP, Op::OP_ADD, Op::OP_SUB, Op::OP_MUL];
    pub fn from_bits(v: u64) -> Option<Op> {
        match v {
            0 => Some(Op::OP_NOP),
            1 => Some(Op::OP_ADD),
            2 => Some(Op::OP_SUB),
            3 => Some(Op::OP_MUL),
            _ => None,
        }
    }
    pub fn bits(self) -> u64 {
        self as u64
    }
    pub fn name(self) -> &'static str {
        match self {
            Op::OP_NOP => "OP_NOP",
            Op::OP_ADD => "OP_ADD",
            Op::OP_SUB => "OP_SUB",
            Op::OP_MUL => "OP_MUL",
        }
    }
    /// Read a signal declared with this type.
    pub fn from_signal(s: &Signal) -> Result<Op> {
        let v = s.get_u64()?;
        Op::from_bits(v).ok_or_else(|| rivet::Error::Msg(format!("{} = {v:#x} is not a op_t value", s.path())))
    }
}

impl TryFrom<u64> for Op {
    type Error = rivet::Error;
    fn try_from(v: u64) -> Result<Op> {
        Op::from_bits(v).ok_or_else(|| rivet::Error::Msg(format!("{v:#x} is not a op_t value")))
    }
}

impl IntoLogicVec for Op {
    fn into_logic_vec(self, width: u32) -> LogicVec {
        LogicVec::from_u64(width, self as u64)
    }
}

impl std::fmt::Display for Op {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.name())
    }
}

/// `typedef struct packed` `cmd_t` (18 bits; first field is the MSB)
#[derive(Clone, Debug, PartialEq)]
pub struct Cmd {
    /// 2 bit(s)
    pub op: Op,
    /// 8 bit(s)
    pub a: u64,
    /// 8 bit(s)
    pub b: u64,
}

impl Cmd {
    pub const WIDTH: u32 = 18;
    pub fn from_bits(v: &LogicVec) -> Result<Cmd> {
        if v.width() != 18 {
            return Err(rivet::Error::Msg(format!("cmd_t: expected 18 bits, got {}", v.width())));
        }
        Ok(Cmd {
            op: Op::from_bits(v.slice(17, 16).to_u64()?)
                .ok_or_else(|| rivet::Error::Msg("cmd_t.op: not a op_t value".into()))?,
            a: v.slice(15, 8).to_u64()?,
            b: v.slice(7, 0).to_u64()?,
        })
    }
    pub fn to_bits(&self) -> LogicVec {
        let mut v = LogicVec::zeros(18);
        let mut hi: u32 = 18;
        hi -= 2;
        for i in 0..2 {
            v.set_bit(hi + i, (LogicVec::from_u64(2, self.op as u64)).bit(i));
        }
        hi -= 8;
        for i in 0..8 {
            v.set_bit(hi + i, (LogicVec::from_u64(8, self.a)).bit(i));
        }
        hi -= 8;
        for i in 0..8 {
            v.set_bit(hi + i, (LogicVec::from_u64(8, self.b)).bit(i));
        }
        v
    }
    pub fn from_signal(s: &Signal) -> Result<Cmd> {
        Cmd::from_bits(&s.get())
    }
    /// Deposit this value on a signal declared with this type.
    pub fn set_on(&self, s: &Signal) {
        s.set(self.to_bits())
    }
}

impl IntoLogicVec for Cmd {
    fn into_logic_vec(self, width: u32) -> LogicVec {
        let mut v = self.to_bits();
        v.resize(width);
        v
    }
}
