//! `rivet new <name>`: scaffold a testbench crate that runs as generated.
//!
//! The generated crate is standalone (it carries an empty `[workspace]`
//! table so it does not join a surrounding workspace) and contains a
//! design, two passing tests, the Verilator entry point and a `cargo test`
//! harness. `--path <dir>` points the dependencies at a Rivet checkout
//! instead of crates.io, which is what the CLI's own tests use.

use std::path::{Path, PathBuf};

/// Turn a directory name into a Rust crate identifier.
fn ident(name: &str) -> String {
    let mut s: String =
        name.chars().map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_lowercase() } else { '_' }).collect();
    if s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}

fn write(root: &Path, rel: &str, body: &str) -> Result<(), String> {
    let p = root.join(rel);
    if let Some(d) = p.parent() {
        std::fs::create_dir_all(d).map_err(|e| format!("{}: {e}", d.display()))?;
    }
    std::fs::write(&p, body).map_err(|e| format!("{}: {e}", p.display()))
}

/// Create a new testbench crate at `dir/name`.
///
/// `rivet_path` makes the generated manifest depend on a local checkout
/// (`rivet = { path = ... }`) instead of the published crate.
pub fn scaffold(name: &str, dir: &Path, rivet_path: Option<&Path>) -> Result<PathBuf, String> {
    let root = if name == "." { dir.to_path_buf() } else { dir.join(name) };
    let crate_name =
        ident(if name == "." { root.file_name().and_then(|s| s.to_str()).unwrap_or("rivet_tb") } else { name });
    if root.join("Cargo.toml").exists() {
        return Err(format!("{} already contains a Cargo.toml", root.display()));
    }
    std::fs::create_dir_all(&root).map_err(|e| format!("{}: {e}", root.display()))?;

    let dep = |extra: &str| -> String {
        match rivet_path {
            Some(p) => format!("{{ path = {:?}{extra} }}", p.join("crates/rivet").display().to_string()),
            None => format!("{{ version = \"0.1\"{extra} }}"),
        }
    };
    let dep_verilator = match rivet_path {
        Some(p) => format!("{{ path = {:?} }}", p.join("crates/rivet-verilator").display().to_string()),
        None => "{ version = \"0.1\" }".to_string(),
    };

    write(
        &root,
        "Cargo.toml",
        &format!(
            r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"
publish = false

# Standalone: this table stops the crate joining a surrounding workspace.
[workspace]

[lib]
# cdylib: loaded by VPI simulators. rlib: linked into the Verilator binary.
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "{crate_name}_verilator"
path = "src/main.rs"
required-features = ["verilator"]

[[test]]
name = "sim"
path = "tests/sim.rs"
harness = false

[dependencies]
rivet = {rivet_dep}

[build-dependencies]
rivet-verilator = {vl_dep}

[features]
default = ["vpi"]
# One backend per simulator: VPI for Icarus and GHDL, VHPI for NVC. A
# library carrying both fails to load on NVC, which resolves eagerly.
vpi = ["rivet/vpi"]
vhpi = ["rivet/vhpi"]
verilator = ["rivet/verilator"]
"#,
            rivet_dep = dep(", default-features = false, features = [\"harness\"]"),
            vl_dep = dep_verilator,
        ),
    )?;

    write(
        &root,
        "rivet.toml",
        r#"[design]
top = "counter"
sources = ["hdl/counter.sv"]

[design.params]
WIDTH = "8"

[sim.icarus]
args = ["-g2012"]

[sim.verilator]
trace = true
"#,
    )?;

    write(
        &root,
        "hdl/counter.sv",
        r#"// A counter with an enable and a synchronous load, for the generated tests.
// The timescale sets the simulator's time precision; without it Icarus
// runs at 1s and sub-second timeouts have no whole number of steps.
`timescale 1ns/1ps
module counter #(
    parameter int WIDTH = 8
) (
    input  logic             clk,
    input  logic             rst_n,
    input  logic             en,
    input  logic             load,
    input  logic [WIDTH-1:0] d,
    output logic [WIDTH-1:0] count
);
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) count <= '0;
    else if (load) count <= d;
    else if (en) count <= count + 1'b1;
  end
endmodule
"#,
    )?;

    write(
        &root,
        "build.rs",
        r#"fn main() {
    // Only the Verilator flow compiles the design into this crate.
    if std::env::var_os("CARGO_FEATURE_VERILATOR").is_some() {
        rivet_verilator::Build::from_manifest().build();
    }
}
"#,
    )?;

    write(
        &root,
        "src/lib.rs",
        r#"//! Generated by `rivet new`. Run it with `rivet run --sim icarus`.

use rivet::prelude::*;

/// Hold reset for two clocks, then release it on an edge.
async fn reset(dut: &Module, clk: Signal) -> rivet::Result<()> {
    let rst_n = dut.signal("rst_n")?;
    rst_n.set(0);
    dut.signal("en")?.set(0);
    dut.signal("load")?.set(0);
    dut.signal("d")?.set(0);
    clk.rising_edge().await;
    clk.rising_edge().await;
    rst_n.set(1);
    clk.rising_edge().await;
    Ok(())
}

#[rivet::test(timeout = 100.us())]
async fn counts_when_enabled(dut: Module) -> rivet::Result<()> {
    let clk = dut.signal("clk")?;
    let _clock = Clock::start(clk, 10.ns());
    reset(&dut, clk).await?;

    let count = dut.signal("count")?;
    dut.signal("en")?.set(1);
    for i in 1..=20u64 {
        clk.rising_edge().await;
        // The edge returns before the flop updates; read after it settles.
        read_only().await;
        assert_eq!(count.get_u64()?, i, "cycle {i}");
        next_time_step().await;
    }
    info!("counted to 20 by {}ns", rivet::now_in(rivet::Unit::Ns));
    Ok(())
}

#[rivet::test(timeout = 100.us())]
async fn load_overrides_count(dut: Module) -> rivet::Result<()> {
    let clk = dut.signal("clk")?;
    let _clock = Clock::start(clk, 10.ns());
    reset(&dut, clk).await?;

    let count = dut.signal("count")?;
    // A fresh random value every run; `rivet run --seed N` replays it.
    let want = rivet::rng().gen_range(0..=255u64);
    dut.signal("d")?.set(want);
    dut.signal("load")?.set(1);
    clk.rising_edge().await;
    read_only().await;
    assert_eq!(count.get_u64()?, want, "loaded value");
    Ok(())
}
"#,
    )?;

    write(
        &root,
        "src/main.rs",
        &format!(
            r#"//! Verilator entry point: `build.rs` links the compiled model in.

// Link the test library so its `#[rivet::test]` registrations are present.
use {crate_name} as _;

fn main() {{
    rivet::verilator::main()
}}
"#
        ),
    )?;

    write(
        &root,
        "tests/sim.rs",
        &format!(
            r#"//! `cargo test` entry point; see `rivet::harness`.
use {crate_name} as _;

fn main() -> std::process::ExitCode {{
    rivet::harness::main()
}}
"#
        ),
    )?;

    write(&root, ".gitignore", "/target\n/sim_build\n")?;

    write(
        &root,
        "README.md",
        &format!(
            r#"# {crate_name}

A Rivet testbench, generated by `rivet new`.

```sh
rivet run --sim icarus      # needs Icarus Verilog 12 or newer
rivet run --sim verilator   # needs Verilator 5.020 or newer
rivet run --waves           # dump waveforms to sim_build/
cargo test                  # the same tests through the cargo harness
```

The design is in `hdl/counter.sv`, the tests are in `src/lib.rs`, and
`rivet.toml` says which sources make up the design.
"#
        ),
    )?;

    Ok(root)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identifiers_are_rust_safe() {
        assert_eq!(ident("my-tb"), "my_tb");
        assert_eq!(ident("2fast"), "_2fast");
        assert_eq!(ident("Mixed.Case"), "mixed_case");
    }

    #[test]
    fn scaffold_writes_a_complete_crate() {
        let dir = std::env::temp_dir().join(format!("rivet-new-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let root = scaffold("demo-tb", &dir, Some(Path::new("/rivet"))).unwrap();
        for f in ["Cargo.toml", "rivet.toml", "build.rs", "hdl/counter.sv", "src/lib.rs", "src/main.rs", "tests/sim.rs"]
        {
            assert!(root.join(f).exists(), "missing {f}");
        }
        let toml = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
        assert!(toml.contains("name = \"demo_tb\""));
        assert!(toml.contains("/rivet/crates/rivet"), "path dependency: {toml}");
        assert!(toml.contains("[workspace]"), "must not join a surrounding workspace");
        // A second scaffold into the same place is refused rather than overwriting.
        assert!(scaffold("demo-tb", &dir, None).is_err());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
